-- Cloud replay aggregation — receives anonymous opt-in uploads from the
-- TCGVibes client. The schema lives at /supabase/migrations/0001_replays.sql
-- and is applied via `supabase db push` (or pasted into the SQL editor on
-- Supabase Dashboard for first-time setup). See docs/REPLAY_BACKEND.md.
--
-- Design notes:
--   - The `replays` table holds the full GameReplay JSON plus extracted
--     metadata (winner, game_mode, archetype) for indexable queries.
--   - Anonymous insert is allowed via RLS; SELECT is service-role only.
--     Service-role connections (offline ETL) can read everything, but the
--     anon key the browser ships with cannot.
--   - Hard CHECK constraints on the table — the RLS policy mirrors them
--     so a future broken policy can't admit garbage rows. Belt-and-
--     suspenders against accidental schema-version drift on the client.
--   - 200 KB JSON cap matches the client-side guard in
--     src/data/replayUpload.ts; oversized payloads short-circuit at the
--     client and (if they slip through) are rejected by the constraint.

create table if not exists replays (
  id uuid primary key default gen_random_uuid(),
  -- Anonymous device-scoped UUID generated by the client and persisted to
  -- localStorage. Lets ETL group a player's games across sessions without
  -- tracking them. Lost on reinstall, by design.
  client_id uuid not null,
  schema_version int not null,
  app_version text not null,
  data_version text not null,
  created_at timestamptz not null,
  completed_at timestamptz,
  winner text,
  game_mode text not null,
  -- Detected client-side at upload time so the offline ETL doesn't need
  -- to re-run archetype detection. Nullable since detection is best-effort.
  p1_archetype text,
  p2_archetype text,
  turn_count int,
  replay jsonb not null,

  constraint winner_valid check (winner is null or winner in ('p1', 'p2')),
  constraint game_mode_valid check (game_mode in ('vsCPU', 'local')),
  constraint schema_version_valid check (schema_version = 2),
  constraint replay_is_object check (jsonb_typeof(replay) = 'object'),
  constraint replay_size_cap check (pg_column_size(replay) < 200000),
  constraint app_version_short check (length(app_version) < 32),
  constraint data_version_short check (length(data_version) < 32)
);

alter table replays enable row level security;

-- Anon insert only — explicit checks mirror the column constraints. If a
-- future policy is misconfigured, the column constraints still hold the
-- line. No SELECT / UPDATE / DELETE policy: anon clients read nothing.
drop policy if exists "anon insert constrained" on replays;
create policy "anon insert constrained" on replays for insert with check (
  schema_version = 2
  and game_mode in ('vsCPU', 'local')
  and (winner is null or winner in ('p1', 'p2'))
  and jsonb_typeof(replay) = 'object'
  and pg_column_size(replay) < 200000
);

create index if not exists replays_created_at_idx on replays (created_at desc);
create index if not exists replays_archetype_idx on replays (p1_archetype, p2_archetype);
create index if not exists replays_client_id_idx on replays (client_id);
