// Runtime accessors for the committed aggregator outputs.
//
// Two artifacts live in src/data/aggregates/, both generated by
// `npm run snapshot:aggregate-rk9`:
//   - cells.json    — matchup matrix cells (eager-loaded, ~210KB)
//   - pairings.json — per-pairing records for drill-down + round filter
//                     (lazy-loaded via dynamic import, ~1.9MB minified)
//
// The cells file mirrors the matchup cells in the meta snapshot but is
// sourced from RK9 pairings × labs labels rather than the snapshot agent.
// DeckDoctor's per-matchup drill-down + round filter read from THESE files
// because they carry the per-pairing detail the snapshot doesn't.

import type { Archetype, Confidence } from "../engine/aiArchetype";

// ---- Cells ---------------------------------------------------------------

export interface AggregateCell {
  hero: Archetype | "unknown";
  villain: Archetype | "unknown";
  wins: number;
  losses: number;
  ties: number;
  winRate: number;
  ci95Low: number;
  ci95High: number;
  sampleSize: number;
  confidence: Confidence;
}

export interface AggregateCellsFile {
  schemaVersion: 1;
  generatedAt: string;
  sourceEvents: string[];
  totalPairings: number;
  labeledPairings: number;
  uniqueLabeledPlayers: number;
  cells: AggregateCell[];
}

// Eager import — cells.json is small (~210KB) and DeckDoctor's MatchupsTab
// reads it on first render. Vite inlines the JSON into the chunk.
import cellsRaw from "./aggregates/cells.json";
export const aggregateCells = cellsRaw as AggregateCellsFile;

// ---- Pairings ------------------------------------------------------------

// The pairings file uses short field names to keep the serialized size down.
// Expand them into a readable shape at read time — callers should never see
// the abbreviated form.
interface SlimPairingPlayer {
  n: string;                // name
  c?: string;               // country (ISO-2)
  a: Archetype | "unknown"; // engine archetype
  al: string | null;        // archetype label (natural-language)
  d: string | null;         // decklist URL
  fr: number | null;        // final rank in standings
  fc: string | null;        // final record string (e.g. "7-2")
}

interface SlimPairing {
  e: number;                // event index into events[]
  r: number;                // round number
  o: "win" | "loss" | "tie"; // outcome from p1's perspective
  p1: SlimPairingPlayer;
  p2: SlimPairingPlayer;
}

interface SlimPairingsFile {
  schemaVersion: 1;
  generatedAt: string;
  events: Array<{ id: string; name: string }>;
  pairings: SlimPairing[];
}

export interface PairingPlayer {
  name: string;
  country?: string;
  archetype: Archetype | "unknown";
  archetypeLabel: string | null;
  decklistUrl: string | null;
  finalRank: number | null;
  finalRecord: string | null;
}

export interface PairingRecord {
  eventId: string;
  eventName: string;
  round: number;
  result: "win" | "loss" | "tie"; // p1's perspective
  p1: PairingPlayer;
  p2: PairingPlayer;
}

// In-process memo so repeated drill-down opens reuse the parse.
let pairingsCache: PairingRecord[] | null = null;
let pairingsPromise: Promise<PairingRecord[]> | null = null;

export async function loadPairings(): Promise<PairingRecord[]> {
  if (pairingsCache) return pairingsCache;
  if (pairingsPromise) return pairingsPromise;
  pairingsPromise = (async () => {
    // Dynamic import keeps the ~1.9MB JSON out of the main bundle —
    // it ships as its own chunk that loads only when DeckDoctor opens
    // the matchup drill-down (or the round filter recomputes cells).
    const mod = await import("./aggregates/pairings.json");
    const file = mod.default as SlimPairingsFile;
    const events = file.events;
    const records: PairingRecord[] = file.pairings.map((sp) => ({
      eventId: events[sp.e].id,
      eventName: events[sp.e].name,
      round: sp.r,
      result: sp.o,
      p1: {
        name: sp.p1.n,
        country: sp.p1.c,
        archetype: sp.p1.a,
        archetypeLabel: sp.p1.al,
        decklistUrl: sp.p1.d,
        finalRank: sp.p1.fr,
        finalRecord: sp.p1.fc,
      },
      p2: {
        name: sp.p2.n,
        country: sp.p2.c,
        archetype: sp.p2.a,
        archetypeLabel: sp.p2.al,
        decklistUrl: sp.p2.d,
        finalRank: sp.p2.fr,
        finalRecord: sp.p2.fc,
      },
    }));
    pairingsCache = records;
    return records;
  })();
  return pairingsPromise;
}

// ---- Filtering + cell recomputation -------------------------------------

// Filter pairings down to a single (hero vs villain) matchup. Returns the
// per-pairing records in event/round order. Each pairing's `result` is
// from p1's perspective — to know whether `hero` won, compare against
// p1.archetype.
export function pairingsForMatchup(
  records: PairingRecord[],
  hero: Archetype | "unknown",
  villain: Archetype | "unknown",
): PairingRecord[] {
  if (hero === villain) return []; // mirror — meaningless in this view
  return records.filter(
    (p) =>
      (p.p1.archetype === hero && p.p2.archetype === villain) ||
      (p.p1.archetype === villain && p.p2.archetype === hero),
  );
}

// Tally (hero, villain) → {wins, losses, ties} from a pairing subset.
// Used by the round-filter feature: filter pairings client-side, then
// recompute cells against the smaller sample.
export function tallyMatchupFromPairings(
  records: PairingRecord[],
  hero: Archetype | "unknown",
  villain: Archetype | "unknown",
): { wins: number; losses: number; ties: number } {
  let wins = 0;
  let losses = 0;
  let ties = 0;
  for (const p of records) {
    if (p.p1.archetype === hero && p.p2.archetype === villain) {
      if (p.result === "win") wins++;
      else if (p.result === "loss") losses++;
      else ties++;
    } else if (p.p1.archetype === villain && p.p2.archetype === hero) {
      // Flip the result: from hero's perspective.
      if (p.result === "win") losses++;
      else if (p.result === "loss") wins++;
      else ties++;
    }
  }
  return { wins, losses, ties };
}

// Wilson 95% CI — mirrors the math in aggregate-rk9-matchups.mjs so cells
// recomputed client-side use the same statistical floor.
export function wilson95FromTally(
  wins: number,
  total: number,
): { winRate: number; ci95Low: number; ci95High: number } {
  if (total <= 0) return { winRate: 0, ci95Low: 0, ci95High: 1 };
  const p = wins / total;
  const z = 1.96;
  const z2 = z * z;
  const denom = 1 + z2 / total;
  const center = (p + z2 / (2 * total)) / denom;
  const margin =
    (z * Math.sqrt((p * (1 - p) + z2 / (4 * total)) / total)) / denom;
  return {
    winRate: p,
    ci95Low: Math.max(0, center - margin),
    ci95High: Math.min(1, center + margin),
  };
}

// Round filter — applies the Strategy 3B handicap. Default cutoff is
// round 5 (excludes the bottom-third elimination noise). The number is
// exposed so the UI can offer "All rounds" / "R5+" / "R7+" toggles.
export function filterByMinRound(
  records: PairingRecord[],
  minRound: number,
): PairingRecord[] {
  if (minRound <= 1) return records;
  return records.filter((p) => p.round >= minRound);
}

// ---- Decklists -----------------------------------------------------------
//
// Generated by `npm run snapshot:fetch-limitless-decklists`. Keyed by the
// labs decklist URL (the same value carried on each PairingRecord.p1/p2),
// so the UI can look up a player's deck directly without an extra index.
// Lazy-loaded via dynamic import — file is multi-MB.

export interface DecklistEntry {
  count: number;
  name: string;
  set: string;
  number: string;
}

export interface DecklistRecord {
  pokemon: DecklistEntry[];
  trainer: DecklistEntry[];
  energy: DecklistEntry[];
}

interface DecklistsFile {
  schemaVersion: 1;
  generatedAt: string;
  decklistCount: number;
  decklists: Record<string, DecklistRecord>;
}

let decklistsCache: Record<string, DecklistRecord> | null = null;
let decklistsPromise: Promise<Record<string, DecklistRecord>> | null = null;

// Lazy-load the decklists file on first request. The file is excluded from
// the main bundle via dynamic import — only DeckDoctor users who expand a
// pairing row pay the download cost.
export async function loadDecklists(): Promise<Record<string, DecklistRecord>> {
  if (decklistsCache) return decklistsCache;
  if (decklistsPromise) return decklistsPromise;
  decklistsPromise = (async () => {
    try {
      const mod = await import("./aggregates/decklists.json");
      const file = mod.default as DecklistsFile;
      decklistsCache = file.decklists;
      return decklistsCache;
    } catch (err) {
      // File missing in repos that haven't run the fetcher yet — degrade
      // gracefully so the rest of the drill-down still renders.
      console.warn("[aggregates] decklists.json not available:", err);
      decklistsCache = {};
      return decklistsCache;
    }
  })();
  return decklistsPromise;
}

// Convenience: total card count in a decklist (should always be 60 for
// a legal Standard deck; useful as a sanity-display in the UI).
export function decklistTotalCount(d: DecklistRecord): number {
  let n = 0;
  for (const arr of [d.pokemon, d.trainer, d.energy]) {
    for (const e of arr) n += e.count;
  }
  return n;
}
