// Meta snapshot — committed JSON files describing what the Standard-format
// field looks like in a window. Snapshots are generated by an off-line
// research agent (see docs/META_SNAPSHOT_AGENT.md) that pulls from the
// Limitless developer API + targeted scraping. They are NOT fetched at
// runtime.
//
// Two distinct dates per snapshot:
//   - generatedAt    : when the JSON file was assembled
//   - coversThrough  : when the latest covered tournament ended
// Freshness gates ALWAYS use coversThrough (data age), not generatedAt.
//
// Quality flag separates fixture-only seed data (test corpora derived from
// in-repo replays) from real research snapshots. Fixture snapshots can never
// produce a user-facing meta grade — analyzeMeta forces "insufficient-data"
// when usableForGrades is false.

import type { Archetype, Confidence } from "../engine/aiArchetype";
import type { RoleTag } from "./cardRoles";

// ---- Top-level snapshot ---------------------------------------------------

export interface MetaSnapshot {
  schemaVersion: 1;
  id: string;                       // "2026-05-prague-osaka" / "fixture-prague-2026"
  format: "Standard";
  region: string;                   // "global" / "EU" / "NA"

  // Quality / suitability flags. Fixture snapshots are for tests, NOT users.
  quality: "fixture" | "research";
  usableForGrades: boolean;         // when false, metaDoctor returns "insufficient-data"

  // Two distinct dates: when we BUILT the file vs. when the data ENDED.
  generatedAt: string;              // ISO — when this file was assembled
  coversFrom: string;               // ISO — earliest tournament included
  coversThrough: string;            // ISO — latest tournament included

  sources: string[];                // URLs to source pages / API endpoints
  minPlayerCount: number;           // tournaments below this threshold excluded
  methodology: string;              // free-form — how data was collected, exclusions

  // Coverage metadata (snapshot-wide). The user-facing grade gates on a
  // per-detected-hero `fieldCoverage` computed inside analyzeMeta — this
  // value is informational only.
  unknownArchetypeShare: number;    // 0-1
  matchupCoverageShare: number;     // 0-1
  onlineShare: number;              // 0-1
  offlineShare: number;             // 0-1
  bo1Share: number;                 // 0-1
  bo3Share: number;                 // 0-1

  tournaments: MetaTournament[];
  archetypes: ArchetypeMetaStats[];
  matchupMatrix: MatchupCell[];
  stockLists: StockListEntry[];
  techCoverage: MetaThreatEntry[];
  coverageNotes: CoverageNote[];
}

// Typed reasons the agent attaches when data isn't fully available. The
// methodology collapsible on the Meta tab renders these so users can see
// exactly why the field's coverage isn't 100%.
export interface CoverageNote {
  category:
    | "rateLimited"
    | "closedDecklists"
    | "archetypeOnlyDecklists"
    | "unmappedArchetypes"
    | "missingApiKey"
    | "scrapeFailed";
  count: number;
  detail?: string;
}

export interface MetaTournament {
  id: string;
  name: string;
  date: string;                     // ISO
  region: string;
  playerCount: number;
  online: boolean;
  sourceUrl: string;
  decklistVisibility: "open" | "archetype-only" | "closed" | "unknown";
}

export interface ArchetypeMetaStats {
  id: Archetype | "unknown";
  metaShare: number;                // 0-1
  conversionRate?: number;          // top-cut rate
  sampleSize: number;
  confidence: Confidence;
  // Resolved representative attackers — names alone are ambiguous, so we
  // carry the gameplayKey + the observed dominant printing.
  mainAttackerCards: ResolvedAttackerRef[];
}

export interface ResolvedAttackerRef {
  cardName: string;
  gameplayKey: string;
  cardId?: string;
  preferredAttack?: string;
}

export interface MatchupCell {
  hero: Archetype | "unknown";
  villain: Archetype | "unknown";
  wins: number;
  losses: number;
  ties: number;                     // 0 if format is BO1 / draws disallowed
  // effectiveWins = wins + 0.5 * ties
  // sampleSize    = wins + losses + ties
  // winRate       = effectiveWins / sampleSize
  winRate: number;
  ci95Low: number;
  ci95High: number;
  sampleSize: number;
  confidence: Confidence;           // derived: high ≥ 30, medium ≥ 10, low < 10
}

export interface StockListEntry {
  archetype: Archetype;
  decksObserved: number;
  cards: StockCardStats[];
}

export interface StockCardStats {
  cardName: string;
  // gameplayKey makes lookups robust against same-name reprints. Required
  // for Pokémon entries; optional for Trainers (where reprints rarely
  // change function).
  gameplayKey?: string;
  inclusionRate: number;            // 0-1
  modeCount: number;                // most common copy-count among decks running it
  modeCountDecks?: number;          // number of decks at modeCount (UI: "8 of 11")
  averageCount: number;
  countDistribution?: Record<number, number>;
  role: "core" | "common" | "tech" | "spicy";
}

export interface MetaThreatEntry {
  archetype: Archetype;
  threats: ThreatClass[];
}

export interface ThreatClass {
  threat: string;                   // human-readable name: "Tool reliance"
  // Multiple answer routes count as covered. Only one needs to be present.
  answerTags?: RoleTag[];
  answerCardNames?: string[];
  minCopies?: number;               // default 1
  confidence: Confidence;
}

// ---- Helpers --------------------------------------------------------------

const MS_PER_DAY = 1000 * 60 * 60 * 24;

function isoDayDelta(iso: string, now: Date): number {
  const ms = now.getTime() - new Date(iso).getTime();
  return Math.floor(ms / MS_PER_DAY);
}

export function generatedAgeDays(s: MetaSnapshot, now: Date = new Date()): number {
  return isoDayDelta(s.generatedAt, now);
}

export function dataAgeDays(s: MetaSnapshot, now: Date = new Date()): number {
  return isoDayDelta(s.coversThrough, now);
}

export function isSnapshotStale(s: MetaSnapshot, now: Date = new Date()): boolean {
  return dataAgeDays(s, now) > 60;
}

export function isSnapshotUnusable(s: MetaSnapshot, now: Date = new Date()): boolean {
  if (!s.usableForGrades) return true;
  return dataAgeDays(s, now) > 90;
}

// Wilson and tie-aware win-rate helpers.
//
// matchupWinRate({wins, losses, ties}) → effective rate, sample, weighted wins.
// wilson95FromRate(winRate, sampleSize) → continuity-corrected 95% CI.
//
// Both throw on sampleSize <= 0 — silently returning 0.5 / [0,1] would hide
// upstream bugs in the snapshot agent.
export function matchupWinRate(r: { wins: number; losses: number; ties: number }):
  { winRate: number; sampleSize: number; effectiveWins: number } {
  const sampleSize = r.wins + r.losses + r.ties;
  if (sampleSize <= 0) {
    throw new Error("matchupWinRate: sampleSize must be > 0");
  }
  const effectiveWins = r.wins + 0.5 * r.ties;
  const winRate = effectiveWins / sampleSize;
  return { winRate, sampleSize, effectiveWins };
}

// Wilson score interval at z = 1.96 (95%). Works on a fractional success
// count (effectiveWins/sampleSize) — the textbook interval is robust to
// non-integer numerators.
export function wilson95FromRate(
  winRate: number,
  sampleSize: number,
): { ci95Low: number; ci95High: number } {
  if (sampleSize <= 0) {
    throw new Error("wilson95FromRate: sampleSize must be > 0");
  }
  const z = 1.96;
  const z2 = z * z;
  const denom = 1 + z2 / sampleSize;
  const center = (winRate + z2 / (2 * sampleSize)) / denom;
  const margin =
    (z * Math.sqrt((winRate * (1 - winRate) + z2 / (4 * sampleSize)) / sampleSize)) /
    denom;
  return {
    ci95Low: Math.max(0, center - margin),
    ci95High: Math.min(1, center + margin),
  };
}

// Confidence label derived from sample size — matches the schema convention.
export function confidenceFromSample(sampleSize: number): Confidence {
  if (sampleSize >= 30) return "high";
  if (sampleSize >= 10) return "medium";
  return "low";
}

// ---- Loader ---------------------------------------------------------------
//
// Snapshots live in src/data/metaSnapshots/*.json. Vite's `import.meta.glob`
// imports them all at build time — small enough to ship inline (each
// snapshot ≈ 30-100KB).
//
// Default behavior: return the freshest non-fixture snapshot whose
// `usableForGrades` is true. Tests pass `allowFixture: true` to access
// fixture data; user-facing UI never does.

const SNAPSHOT_GLOB = import.meta.glob("./metaSnapshots/*.json", {
  eager: true,
  import: "default",
}) as Record<string, MetaSnapshot>;

export async function loadLatestSnapshot(
  opts: { allowFixture?: boolean } = {},
): Promise<MetaSnapshot | null> {
  const all = Object.values(SNAPSHOT_GLOB);
  const candidates = all.filter((s) => {
    if (s.quality === "fixture" && !opts.allowFixture) return false;
    if (!s.usableForGrades && !opts.allowFixture) return false;
    return true;
  });
  if (candidates.length === 0) return null;
  candidates.sort((a, b) => b.coversThrough.localeCompare(a.coversThrough));
  return candidates[0];
}

// Synchronous variant — useful in tests.
export function loadLatestSnapshotSync(
  opts: { allowFixture?: boolean } = {},
): MetaSnapshot | null {
  const all = Object.values(SNAPSHOT_GLOB);
  const candidates = all.filter((s) => {
    if (s.quality === "fixture" && !opts.allowFixture) return false;
    if (!s.usableForGrades && !opts.allowFixture) return false;
    return true;
  });
  if (candidates.length === 0) return null;
  candidates.sort((a, b) => b.coversThrough.localeCompare(a.coversThrough));
  return candidates[0];
}

// All snapshots (fixture + research) — used by the validation test.
export function allSnapshots(): MetaSnapshot[] {
  return Object.values(SNAPSHOT_GLOB);
}
